<?php
/**
 * Keyword → subcategory name hints for title-based category suggestions.
 * Names must match enabled subcategory labels (see admin categories).
 */

if (isset($_SERVER['SCRIPT_FILENAME'])
    && basename((string) $_SERVER['SCRIPT_FILENAME']) === 'category_suggest.php'
) {
    exit;
}

/**
 * Curated synonyms / brands / common items → leaf category name.
 *
 * @return array<string,string> keyword (lowercase) => subcategory name
 */
function pngm_category_suggest_keywords()
{
    return array(
        // Vehicles
        'hilux' => 'Cars',
        'toyota' => 'Cars',
        'corolla' => 'Cars',
        'camry' => 'Cars',
        'landcruiser' => 'Cars',
        'land cruiser' => 'Cars',
        'prado' => 'Cars',
        'rav4' => 'Cars',
        'honda' => 'Cars',
        'civic' => 'Cars',
        'mazda' => 'Cars',
        'nissan' => 'Cars',
        'navara' => 'Cars',
        'mitsubishi' => 'Cars',
        'triton' => 'Cars',
        'subaru' => 'Cars',
        'ford' => 'Cars',
        'ranger' => 'Cars',
        'hyundai' => 'Cars',
        'kia' => 'Cars',
        'bmw' => 'Cars',
        'mercedes' => 'Cars',
        'sedan' => 'Cars',
        'suv' => 'Cars',
        'ute' => 'Cars',
        '4wd' => 'Cars',
        '4x4' => 'Cars',
        'car' => 'Cars',
        'tyre' => 'Car Parts & Accessories',
        'tire' => 'Car Parts & Accessories',
        'rim' => 'Car Parts & Accessories',
        'battery' => 'Car Parts & Accessories',
        'radiator' => 'Car Parts & Accessories',
        'muffler' => 'Car Parts & Accessories',
        'truck' => 'Trucks & Commercial',
        'dump truck' => 'Trucks & Commercial',
        'bus' => 'Buses & Vans',
        'van' => 'Buses & Vans',
        'boat' => 'Boats & Marine',
        'dinghy' => 'Boats & Marine',
        'outboard' => 'Boats & Marine',
        'motorcycle' => 'Motorcycles',
        'motorbike' => 'Motorcycles',
        'bike' => 'Motorcycles',
        'scooter' => 'Motorcycles',
        'yamaha' => 'Motorcycles',
        'suzuki' => 'Motorcycles',
        'kawasaki' => 'Motorcycles',
        'excavator' => 'Heavy Machinery',
        'bulldozer' => 'Heavy Machinery',
        'loader' => 'Heavy Machinery',
        'caravan' => 'RVs & Caravans',
        'rv' => 'RVs & Caravans',

        // Phones & Electronics
        'iphone' => 'Mobile Phones',
        'samsung' => 'Mobile Phones',
        'galaxy' => 'Mobile Phones',
        'android' => 'Mobile Phones',
        'smartphone' => 'Mobile Phones',
        'mobile' => 'Mobile Phones',
        'phone' => 'Mobile Phones',
        'nokia' => 'Mobile Phones',
        'huawei' => 'Mobile Phones',
        'oppo' => 'Mobile Phones',
        'xiaomi' => 'Mobile Phones',
        'charger' => 'Phone Accessories',
        'earphone' => 'Phone Accessories',
        'earbuds' => 'Phone Accessories',
        'airpods' => 'Phone Accessories',
        'phonecase' => 'Phone Accessories',
        'laptop' => 'Computers & Laptops',
        'macbook' => 'Computers & Laptops',
        'notebook' => 'Computers & Laptops',
        'computer' => 'Computers & Laptops',
        'pc' => 'Computers & Laptops',
        'desktop' => 'Computers & Laptops',
        'monitor' => 'Computer Accessories',
        'keyboard' => 'Computer Accessories',
        'mouse' => 'Computer Accessories',
        'printer' => 'Computer Accessories',
        'tv' => 'TVs & Home Entertainment',
        'television' => 'TVs & Home Entertainment',
        'smart tv' => 'TVs & Home Entertainment',
        'speaker' => 'Audio & Speakers',
        'bluetooth speaker' => 'Audio & Speakers',
        'headset' => 'Audio & Speakers',
        'camera' => 'Cameras',
        'dslr' => 'Cameras',
        'gopro' => 'Cameras',
        'playstation' => 'Gaming & Consoles',
        'xbox' => 'Gaming & Consoles',
        'nintendo' => 'Gaming & Consoles',
        'ps4' => 'Gaming & Consoles',
        'ps5' => 'Gaming & Consoles',
        'switch' => 'Gaming & Consoles',
        'fridge' => 'Home Appliances',
        'refrigerator' => 'Home Appliances',
        'freezer' => 'Home Appliances',
        'washing machine' => 'Home Appliances',
        'washer' => 'Home Appliances',
        'dryer' => 'Home Appliances',
        'microwave' => 'Home Appliances',
        'aircon' => 'Home Appliances',
        'air conditioner' => 'Home Appliances',
        'fan' => 'Home Appliances',

        // Home
        'sofa' => 'Furniture',
        'couch' => 'Furniture',
        'bed' => 'Furniture',
        'mattress' => 'Furniture',
        'table' => 'Furniture',
        'chair' => 'Furniture',
        'wardrobe' => 'Furniture',
        'desk' => 'Furniture',
        'kettle' => 'Kitchen & Dining',
        'toaster' => 'Kitchen & Dining',
        'blender' => 'Kitchen & Dining',
        'cookware' => 'Kitchen & Dining',
        'pots' => 'Kitchen & Dining',
        'pans' => 'Kitchen & Dining',
        'plates' => 'Kitchen & Dining',
        'cutlery' => 'Kitchen & Dining',
        'rice cooker' => 'Kitchen & Dining',
        'curtain' => 'Home Decor',
        'rug' => 'Home Decor',
        'lamp' => 'Home Decor',
        'mower' => 'Garden & Outdoor',
        'lawnmower' => 'Garden & Outdoor',
        'hose' => 'Garden & Outdoor',
        'drill' => 'Tools & Equipment',
        'hammer' => 'Tools & Equipment',
        'saw' => 'Tools & Equipment',
        'generator' => 'Generators & Solar',
        'solar' => 'Generators & Solar',
        'inverter' => 'Generators & Solar',
        'cement' => 'Building Materials',
        'timber' => 'Building Materials',
        'roofing' => 'Building Materials',

        // Fashion
        'shirt' => "Men's Clothing",
        'tshirt' => "Men's Clothing",
        't-shirt' => "Men's Clothing",
        'jeans' => "Men's Clothing",
        'dress' => "Women's Clothing",
        'skirt' => "Women's Clothing",
        'blouse' => "Women's Clothing",
        'sneakers' => 'Shoes',
        'boots' => 'Shoes',
        'sandals' => 'Shoes',
        'handbag' => 'Bags & Accessories',
        'backpack' => 'Bags & Accessories',
        'watch' => 'Jewelry & Watches',
        'necklace' => 'Jewelry & Watches',
        'ring' => 'Jewelry & Watches',
        'perfume' => 'Beauty Products',
        'makeup' => 'Beauty Products',
        'lipstick' => 'Beauty Products',

        // Babies / toys
        'pram' => 'Baby Equipment',
        'stroller' => 'Baby Equipment',
        'cot' => 'Baby Equipment',
        'nappy' => 'Baby Equipment',
        'toy' => 'Toys & Games',
        'lego' => 'Toys & Games',
        'puzzle' => 'Toys & Games',

        // Sports
        'football' => 'Sports Equipment',
        'soccer' => 'Sports Equipment',
        'rugby' => 'Sports Equipment',
        'gym' => 'Sports Equipment',
        'dumbbell' => 'Sports Equipment',
        'bicycle' => 'Bicycles',
        'mountain bike' => 'Bicycles',
        'fishing' => 'Fishing',
        'rod' => 'Fishing',
        'tent' => 'Camping & Outdoor',
        'guitar' => 'Musical Instruments',
        'keyboard piano' => 'Musical Instruments',
        'ukulele' => 'Musical Instruments',
        'book' => 'Books',
        'novel' => 'Books',
        'textbook' => 'Books',

        // Agriculture
        'tractor' => 'Farm Machinery & Equipment',
        'plough' => 'Farm Machinery & Equipment',
        'cow' => 'Livestock',
        'pig' => 'Livestock',
        'chicken' => 'Livestock',
        'goat' => 'Livestock',
        'seed' => 'Seeds & Plants',
        'seedling' => 'Seeds & Plants',
        'fertilizer' => 'Fertilizers & Chemicals',
        'feed' => 'Animal Feed',

        // Business
        'forklift' => 'Industrial Equipment',
        'photocopier' => 'Office Equipment',
        'office chair' => 'Office Equipment',
        'pos' => 'Retail Equipment',
        'scaffolding' => 'Construction Equipment',

        // Pets
        'puppy' => 'Dogs',
        'dog' => 'Dogs',
        'kitten' => 'Cats',
        'cat' => 'Cats',
        'parrot' => 'Birds',
        'aquarium' => 'Fish',
        'dog food' => 'Pet Supplies',
        'cat food' => 'Pet Supplies',

        // Property
        'house' => 'Houses for Sale',
        'apartment' => 'Apartments for Sale',
        'flat' => 'Apartments for Sale',
        'room' => 'Rooms for Rent',
        'land' => 'Land',
        'block' => 'Land',
        'office space' => 'Commercial Property',
        'shop' => 'Commercial Property',

        // Jobs / Services (common titles)
        'driver' => 'Logistics & Transport',
        'security guard' => 'Security',
        'teacher' => 'Education & Training',
        'mechanic' => 'Automotive Services',
        'plumber' => 'Repair & Maintenance',
        'electrician' => 'Repair & Maintenance',
        'cleaner' => 'Cleaning Services',
        'tutoring' => 'Training & Tutoring',
        'tutor' => 'Training & Tutoring',
    );
}
