SET FOREIGN_KEY_CHECKS=0;


DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_wac_item;
CREATE TABLE /*TABLE_PREFIX*/t_wac_item (
  fk_i_item_id INT UNSIGNED NOT NULL,
  s_phone VARCHAR(50) DEFAULT NULL,
  b_enable TINYINT(1) DEFAULT 1,
  i_clicks INT(10) DEFAULT 0,
  i_views INT(10) DEFAULT 0,

  PRIMARY KEY (fk_i_item_id),
  FOREIGN KEY (fk_i_item_id) REFERENCES /*TABLE_PREFIX*/t_item (pk_i_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';


SET FOREIGN_KEY_CHECKS=1;